---
stages:
- name: Build Stage
  inputs:
  - url: https://git.ng.bluemix.net/milbuild/jes-test-push-20170425204330821.git
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      # your script here

      echo "Hello World"
      echo "Goodbye World"
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: milbuild@us.ibm.com
      space: dev
      application: jes-test-push-20170425204330821
    script: "#!/bin/bash\n# Push app\n\nif ! cf app $CF_APP; then  \n  cf push $CF_APP\n\
      else\n  OLD_CF_APP=${CF_APP}-OLD-$(date +\"%s\")\n  rollback() {\n    set +e\
      \  \n    if cf app $OLD_CF_APP; then\n      cf logs $CF_APP --recent\n     \
      \ cf delete $CF_APP -f\n      cf rename $OLD_CF_APP $CF_APP\n    fi\n    exit\
      \ 1\n  }\n  set -e\n  trap rollback ERR\n  cf rename $CF_APP $OLD_CF_APP\n \
      \ cf push $CF_APP\n  cf delete $OLD_CF_APP -f\nfi\n# Export app name and URL\
      \ for use in later Pipeline jobs\nexport CF_APP_NAME=\"$CF_APP\"\nexport APP_URL=http://$(cf\
      \ app $CF_APP_NAME | grep urls: | awk '{print $2}')\n# View logs\n#cf logs \"\
      ${CF_APP}\" --recent\n"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
